// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtinzfnhrjmicmjnevxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0aW56Zm5ocmptaWNtam5ldnhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMzQ5MDMsImV4cCI6MjA2OTcxMDkwM30.P4z0XC2u7FDLrFnVmr3B4wEByBYDR92JVGqI7PGN9II";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});